OxiPulso/Mediciones/models.py
from OxiPulso import db
import pandas as pd
import os
from OxiPulso.Autenticacion.models import Usuario
from flask import send_file
import random
from datetime import date

class Mediciones(db.Model):
    _tablename_ = "mediciones"
    id = db.Column(db.Integer, primary_key=True)
    usuario_id = db.Column(db.Integer, db.ForeignKey('usuarios.id'), nullable=False)
    bpm = db.Column(db.Integer, nullable=False)
    spo2 = db.Column(db.Integer, nullable=False)
    fecha = db.Column(db.Date, nullable=False)
    hora = db.Column(db.Time, nullable=False)
    usuario = db.relationship('Usuario', backref=db.backref('mediciones', lazy=True))


    def __init__(self, usuario_id, bpm, spo2, fecha, hora):
        self.usuario_id = usuario_id
        self.bpm = bpm
        self.spo2 = spo2
        self.fecha = fecha
        self.hora = hora
    
    def __repr__(self):
        return f"BPM: {self.bpm}\nSPO2: {self.spo2}\nFecha: {self.fecha}\nHora: {self.hora}"
    
    def to_dict(self):
        return {
            'id': self.id,
            'usuario_id': self.usuario_id,
            'bpm': self.bpm,
            'spo2': self.spo2,
            'fecha': self.fecha.isoformat(),
            'hora': str(self.hora.strftime('%H:%M'))
        }
    
    def to_dict_admon(self):
        return {
            'id': self.id,
            'usuario_nombre':self.usuario.nombre,
            'bpm': self.bpm,
            'spo2': self.spo2,
            'fecha': self.fecha.isoformat(),

        }
        
    def to_dict_all(self):
        nacimiento = self.usuario.fechaNacimiento
        hoy = date.today()
        edad = hoy.year - nacimiento.year - ((hoy.month, hoy.day) < (nacimiento.month, nacimiento.day))

        return {
            'id': self.id,
            'nombre':self.usuario.nombre,
            'edad':edad,
            'sexo':self.usuario.sexo,
            'bpm': self.bpm,
            'spo2': self.spo2,
            'fecha': self.fecha.isoformat(),

        }

    
    @classmethod
    def obtener_datos(cls, id):
        datos = cls.query.filter_by(usuario_id=id).all()
        datos_dict = [dato.to_dict() for dato in datos]
        # print(datos_dict)
        return datos_dict
        
    @classmethod
    def obtener_datos_admon(cls):
        datos = cls.query.all()
        datos_dict_admon = [dato.to_dict_admon() for dato in datos]
        # print(datos_dict_admon)
        return datos_dict_admon
    
    @classmethod
    def obtener_todos_datos(cls):
        datos = cls.query.all()
        datos_dict_admon = [dato.to_dict_all() for dato in datos]
        # print(datos_dict_admon)
        return datos_dict_admon


    
    @classmethod
    def descargar_csv(cls, usuario_id):
        usuario = Usuario.query.filter_by(id=usuario_id).first()
        
        if not usuario:
            return "Usuario no encontrado", 404
        
        datos = db.session.query(Usuario, Mediciones).join(
            Mediciones, Usuario.id == Mediciones.usuario_id
        ).with_entities(
            Usuario.nombre, Mediciones.bpm, Mediciones.spo2, Mediciones.hora, Mediciones.fecha
        ).filter(
            Usuario.id == usuario_id
        ).all()

        df = pd.DataFrame(datos, columns=['Nombre', 'BPM', 'SPO2', 'Hora', 'Fecha'])

        # Define la carpeta correcta
        base_dir = os.path.dirname(os.path.abspath(__file__))  # Base directory of the script
        carpeta = os.path.join(base_dir, 'Oxipulso', 'archivos')
        
        if not os.path.exists(carpeta):
            os.makedirs(carpeta)

        # Asegúrate de limpiar el nombre del archivo de caracteres especiales
        nombre_archivo = f"{usuario.nombre}.csv".replace(" ", "_")
        ruta = os.path.join(carpeta, nombre_archivo)

        df.to_csv(ruta, index=False)
        
        print("Se descargó")
        return send_file(ruta, as_attachment=True)
    
    @classmethod
    def descargar_csv_usuario(cls, usuario_id):
        usuario = Usuario.query.filter_by(id=usuario_id).first()
    
        datos = db.session.query(Usuario, Mediciones).join(Mediciones,
            Usuario.id == Mediciones.usuario_id).with_entities(Usuario.nombre, Mediciones.bpm, Mediciones.spo2, Mediciones.hora, Mediciones.fecha).filter(Usuario.id == usuario_id).all()

    
        df = pd.DataFrame(datos, columns=['Nombre', 'BPM', 'SPO2', 'Hora', 'Fecha'])

        carpeta = 'Oxipulso/archivos'
        
        if not os.path.exists(carpeta):
            os.makedirs(carpeta)

        ruta = os.path.join(carpeta, f"{usuario.nombre}.csv")

        print("Se descargó")
        # Convertimos el dataframe en un archivo excel y lo guardamos
        df.to_csv(ruta, index=False)
        return send_file(ruta, as_attachment=True)
        
    @classmethod
    def descargar_csv_all(cls):
        datos = db.session.query(Usuario, Mediciones).join(
            Mediciones, Usuario.id == Mediciones.usuario_id
        ).with_entities(
            Usuario.nombre, Mediciones.bpm, Mediciones.spo2, Mediciones.hora, Mediciones.fecha
        ).all()
        print(datos)
        df = pd.DataFrame(datos, columns=['Nombre', 'BPM', 'SPO2', 'Hora', 'Fecha'])
        
        # Define la carpeta correcta
        base_dir = os.path.dirname(os.path.abspath(__file__))  
        carpeta = os.path.join(base_dir, 'archivos')
        
        if not os.path.exists(carpeta):
            os.makedirs(carpeta)

        # Asegúrate de limpiar el nombre del archivo de caracteres especiales
        nombre_archivo = "todos_los_datos.csv".replace(" ", "_")
        ruta = os.path.join(carpeta, nombre_archivo)

        df.to_csv(ruta, index=False)
        
        print("Se descargó")
        return send_file(ruta, as_attachment=True)
    
    @classmethod
    def descargar_datos_usuario(cls, usuario_id):
        usuario = Usuario.query.filter_by(id=usuario_id).first()
        datos = cls.query.filter_by(usuario_id=usuario_id).all()
        datos_dict = [dato.to_dict() for dato in datos]
        return datos_dict
    

OxiPulso/Administrador/views.py
from flask import (
    render_template,
    Blueprint,
    request,
    jsonify,
    session,
    redirect,
    url_for 
)
from OxiPulso.Mediciones.models import Mediciones
from OxiPulso.Autenticacion.models import Usuario
from .estadisticas import basicos
from dotenv import load_dotenv
import os

administrador = Blueprint('administrador', __name__)

load_dotenv()

USER_ADMIN = os.getenv('USER_ADMIN')
PASSWORD_ADMIN = os.getenv('PASSWORD_ADMIN')

@administrador.route('/administrador')
def inicio():
    return render_template("administrador/admonvista.html")

@administrador.route('/adminlogout')
def cerrarSesion():
    session['admin'] = None
    
    return redirect(url_for('administrador.inicio'))


@administrador.route('/administrador/login', methods=['GET', 'POST'])
def iniciarSesion():
    
    session.clear()
    
    if request.method == 'POST':
        usuario = request.form.get('usuario')
        password = request.form.get('contraseña')
        
        if not usuario:
            return render_template("administrador/login.html", alert='Ingrese el usuario')
        if not password:
            return render_template("administrador/login.html", alert='Ingrese la contraseña')
        print(usuario, password)
        print(USER_ADMIN, PASSWORD_ADMIN)
        if usuario == USER_ADMIN and password == PASSWORD_ADMIN:
            session['admin'] = 1
            return redirect(url_for('administrador.inicio'))
        else:
            return render_template("administrador/login.html", alert='Usuario o contraseña incorrectos')
    return render_template("administrador/login.html")


@administrador.route('/administrador/usuarios')
def obtener_usuarios():
    usuarios = Usuario.obtener_datos_admon()  
    return jsonify(success=True, usuarios=usuarios)

@administrador.route('/administrador/mediciones', methods=['GET', 'POST'])
def obtener_mediciones():
    if request.method == 'POST':
        user = request.form.get('usuario')
        usuario = Usuario.query.filter_by(usuario=user).first()
        usuario_id = usuario.id
        print(usuario_id)
        mediciones = Mediciones.obtener_datos(id=usuario_id)
        return jsonify(success=True, mediciones=mediciones)
    else:
        print("hola")
        mediciones = Mediciones.obtener_datos_admon() 
        return jsonify(success=True, mediciones=mediciones)
    
@administrador.route('/admon/mediciones_vista')
def mediciones_vista():
    return render_template("administrador/mediciones.html")

@administrador.route('/admon/usuarios_vista')
def usuarios_vista():
    return render_template("administrador/usuarios.html")

@administrador.route('/administrador/descarga/mediciones')
def descargar_datos_medicion():
    return Mediciones.descargar_csv_all()
    

@administrador.route('/administrador/descarga/usuarios')
def descargar_datos_usuarios():
    usuario_id = session.get('usuario_id')
    if usuario_id:
        #return render_template("mediciones/historial.html", mediciones=mediciones)
        return Usuario.descargar_csv(id=usuario_id)
    else:
        return Usuario.descargar_csv_all()    
    
@administrador.route('/administrador/estadisticas')
def estadisticas():
    (
        bpm_max_data,
        bpm_min_data,
        spo2_max_data,
        spo2_min_data,
        timeline_base64,
        barras_base64,
    ) = basicos()

    return render_template(
        'administrador/estadisticas.html',
        bpm_max_data=bpm_max_data,
        bpm_min_data=bpm_min_data,
        spo2_max_data=spo2_max_data,
        spo2_min_data=spo2_min_data,
         timeline_base64=timeline_base64,
        barras_base64=barras_base64
    )
    
@administrador.route('/administrador/all_mediciones')
def all_mediciones():
    mediciones = Mediciones.obtener_todos_datos()
    return jsonify(success=True, mediciones=mediciones)

@administrador.route('/administrador/descargar_datos_usuario/<int:id>')
def descargar_datos_usuario(id):
    return Mediciones.descargar_csv(id)

OxiPulso/Mediciones/views.py
from flask import (
    render_template,
    Blueprint,
    request,
    jsonify,
    session,
    redirect,
    url_for 
)
from OxiPulso.Mediciones.models import Mediciones

from OxiPulso.funciones import init_mqtt, wait_for_message
from OxiPulso import app, db
from datetime import datetime
from dotenv import load_dotenv
import os

load_dotenv()
# Iniciar MQTT
topic = os.environ.get('MQTT_TOPIC')
mqtt_client = init_mqtt(app, topic)


mediciones = Blueprint('mediciones', __name__)


@mediciones.route('/mediciones', methods=['GET', 'POST'])
def medicion():
    return render_template("mediciones/mediciones.html")

@mediciones.route('/tutorial')
def tutorial():
    return render_template("mediciones/tutorial.html")

@app.route('/mediciones/medir', methods=['POST'])
def publish_message():
    request_data = request.form['message']
    print(request_data)
    publish_result = mqtt_client.publish(topic, request_data)
    print(publish_result)
    
    # Espera a que se publique el valor medido
    measured_value = wait_for_message()
    # measured_value = {"HR":51,"SPO2":90}
    # measured_value = None
    
    if measured_value is not None:
        
        if "error" in measured_value:
            print(measured_value)
            return jsonify(success=False, error=measured_value["error"])
        
        print(measured_value)
        
        usuario_id = session.get('usuario_id')
        if usuario_id:
            try:
                nueva_medicion = Mediciones(
                    usuario_id=usuario_id,
                    bpm=measured_value["HR"],
                    spo2=measured_value["SPO2"],
                    fecha=datetime.today().strftime("%Y-%m-%d"),
                    hora=datetime.now().strftime("%H:%M:%S")
                )
                
                db.session.add(nueva_medicion)
                db.session.commit()
           
            except Exception as e:
               
                db.session.rollback()
                return jsonify(success=False, error="Error inesperado al guardar la medición")
        
        return jsonify(success=True, hr=measured_value["HR"], spo2=measured_value["SPO2"])
    else:
        return jsonify(success=False, error="No se recibió el valor del sensor a tiempo")
    
@mediciones.route('/historial')
def historial():
    usuario_id = session.get('usuario_id')
    if usuario_id:
        mediciones = Mediciones.obtener_datos(id=usuario_id)
        # print(mediciones)
        return render_template("mediciones/historial.html", mediciones=mediciones)
        # return render_template("mediciones/historial.html")
    else:
        return redirect(url_for('usuarios.iniciarSesion'))
    
@mediciones.route('/mediciones/historial/datos')
def historial_obtener_datos():
    usuario_id = session.get('usuario_id')
    if usuario_id:
        mediciones = Mediciones.obtener_datos(id=usuario_id)
        #return render_template("mediciones/historial.html", mediciones=mediciones)
        return jsonify(success=True, mediciones=mediciones)
    else:
        return redirect(url_for('usuarios.iniciarSesion'))
    

@mediciones.route('/mediciones/descargar')
def descargar():
    usuario_id = session.get('usuario_id')
    if usuario_id:
        return Mediciones.descargar_csv(usuario_id)
    else:
        return jsonify(success=False, error="No se ha iniciado sesión")
    

@mediciones.route('/mediciones/resumen')
def resumen():   
    return render_template("mediciones/resumen.html")
    
    

OxiPulso/templates/administrador/admonvista.html
{% extends "/administrador/admon.html" %}
{% block title %}Inicio{% endblock %}

{% block content %}
<main
class="relative h-screen bg-cover bg-center"
style="
  background-image: url('../static/img/bg-home.png');
"
>
<div class="absolute inset-0 flex items-center justify-center">
  <h1 class="text-white text-4xl font-bold">Bienvenidos a OxiPulso-Administrador</h1>
</div>
</main>
{% endblock %}

OxiPulso/templates/administrador/login.html
{% extends "administrador/admon.html" %}
{% block title %}Mediciones{% endblock %}

{% block content%}

<main class="mt-28 mb-10">
    <h1 class="font-bold text-blue-700 text-4xl text-center mb-8">Iniciar Sesión</h1>
    <form action="/administrador/login" method="POST" class="max-w-md mx-auto bg-white p-8 rounded-lg shadow-md ">
     
        <div class="mb-5">
            <label for="usuario" class="block mb-2 text-sm font-medium text-gray-900 ">Tu usuario</label>
            <input type="text" id="usuario" name="usuario" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " placeholder="Usuario" required />
          </div>
      <div class="mb-5">
        <label for="contraseña" class="block mb-2 text-sm font-medium text-gray-900 ">Contraseña</label>
        <input type="password" id="password" name="contraseña" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " required />
      </div>
     
      
      <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center   ">Iniciar Sesión</button>
     
    </form>
  </main>

{% endblock %}

OxiPulso/templates/administrador/mediciones.html
{% extends "administrador/admon.html" %}
{% block title %}Mediciones{% endblock %}

{% block content%}
<main class="mt-28 mb-20">
<div class="overflow-x-auto bg-white shadow-md sm:rounded-lg p-4 tabla-scroll">
  <span class="self-center text-2xl text-blue-700 font-semibold whitespace-nowrap  ">Mediciones Usuarios</span>
  <div class="md:flex">
 
    <button
      type="button"
      class="text-white bg-blue-700 my-6 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center"
    >
    <a href="{{ url_for('administrador.descargar_datos_medicion') }}">Descargar Datos de todos los usuarios</a>
    </button>
  </div> 
    <table id="productTable" class="min-w-full divide-y divide-gray-200">
      <thead>
        <tr class="bg-blue-700 text-xs text-white font-bold uppercase">
                <th onclick="ordenarColumna(0)" class="px-6 py-3 text-left cursor-pointer">
                  Nombre
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th onclick="ordenarColumna(1)" class="px-6 py-3 text-left cursor-pointer">
                  Bpm
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th onclick="ordenarColumna(2)" class="px-6 py-3 text-left cursor-pointer">
                  Spo2
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th onclick="ordenarColumna(3)" class="px-6 py-3 text-left cursor-pointer">
                  Fecha
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                
              </tr>
        </tr>
      </thead>
      <tbody id="tableBodymediciones">
        <!-- Aquí se insertarán las filas de la tabla -->
      </tbody>
    </table>
  </div>

  <div id="paginacion" class="pagination flex justify-center items-center mt-4"></div>
</main>

<script src="{{ url_for('static', filename='js/tablemedicion.js') }}"></script>
{% endblock %}

OxiPulso/templates/administrador/usuarios.html
{% extends "administrador/admon.html" %}
{% block title %}Usuarios{% endblock %}

{% block content%}
<main class="mt-28 mb-20">
<div class="overflow-x-auto bg-white shadow-md sm:rounded-lg p-4 tabla-scroll">
  <span class="self-center text-2xl text-blue-700 font-semibold whitespace-nowrap  ">Datos Usuarios</span>
  <div class=" md:flex">
          
    <button
      type="button"
      class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center mb-6"
    >
    <a href="{{ url_for('administrador.descargar_datos_usuarios') }}">Descargar Datos</a>
    </button> 
  </div>
    <table id="productTable" class="min-w-full divide-y divide-gray-200">
      <thead>
        <tr class="bg-blue-700 text-xs text-white font-bold uppercase">
                <th onclick="ordenarColumna(0)" class="px-6 py-3 text-left cursor-pointer">
                  Nombre
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th onclick="ordenarColumna(1)" class="px-6 py-3 text-left cursor-pointer">
                  correo
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th onclick="ordenarColumna(2)" class="px-6 py-3 text-left cursor-pointer">
                  Nacimiento
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th onclick="ordenarColumna(3)" class="px-6 py-3 text-left cursor-pointer">
                  sexo
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th class="px-6 py-3 text-left cursor-pointer">
                  Acciones
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                
              </tr>
        </tr>
      </thead>
      <tbody id="tableBodyuser">
        <!-- Aquí se insertarán las filas de la tabla -->
      </tbody>
    </table>
  </div>

  <div id="paginacion" class="pagination flex justify-center items-center mt-4"></div>
</main>

<script src="{{ url_for('static', filename='js/tableuser.js') }}"></script>
{% endblock %}