OxiPulso/Autenticacion/models.py
from OxiPulso import db
import pandas as pd
import os
from flask import send_file,jsonify

class Usuario(db.Model):
    __tablename__ = 'usuarios'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(100), nullable=False)
    fechaNacimiento = db.Column(db.Date, nullable=False)
    sexo = db.Column(db.String(10), nullable=False)
    usuario = db.Column(db.String(50), nullable=False, unique=True)
    correo = db.Column(db.String(100), nullable=False, unique=True)
    contraseña = db.Column(db.String(250), nullable=False)
    fechaRegistro = db.Column(db.DateTime, nullable=False)
    
    def __init__(self, nombre, fechaNacimiento, sexo, usuario, correo, contraseña, fechaRegistro):
        self.nombre = nombre
        self.fechaNacimiento = fechaNacimiento
        self.sexo = sexo
        self.usuario = usuario
        self.correo = correo
        self.contraseña = contraseña
        self.fechaRegistro = fechaRegistro
    
    def __repr__(self):
        return f"Nombre: {self.nombre}\nUsuario: {self.usuario}\nCorreo: {self.correo}"

    def to_dict(self):
        return {
            'id': self.id,
            'sexo': self.sexo,
            'nombre': self.nombre,
            'correo': self.correo,
            'nacimiento': self.fechaNacimiento,

        }
    
    
    @classmethod
    def obtener_datos_admon(cls):
        datos = cls.query.all()
        datos_dict_admon = [dato.to_dict() for dato in datos]
        return datos_dict_admon
        
    @classmethod
    def descargar_csv(cls, usuario_id):
        usuario = cls.query.filter_by(id=usuario_id).first()
        
        if not usuario:
            return jsonify({"error": "Usuario no encontrado"}), 404
        
        datos = [usuario.to_dict()]

        df = pd.DataFrame(datos)

        carpeta = 'OxiPulso/archivos'
        
        if not os.path.exists(carpeta):
            os.makedirs(carpeta)

        ruta = os.path.join(carpeta, f"{usuario.nombre}.csv")

        df.to_csv(ruta, index=False)

        print("Se descargó")
        return send_file(ruta, as_attachment=True)
        
    @classmethod
    def descargar_csv_all(cls):
        datos = db.session.query(
            Usuario.id, 
            Usuario.nombre, 
            Usuario.fechaNacimiento, 
            Usuario.sexo, 
            Usuario.usuario, 
            Usuario.correo
        ).all()

        df = pd.DataFrame(datos, columns=['ID', 'Nombre', 'Fecha de Nacimiento', 'Sexo', 'Usuario', 'Correo'])

        base_dir = os.path.dirname(os.path.abspath(__file__))  # Base directory of the script
        carpeta = os.path.join(base_dir, 'archivos')
        
        if not os.path.exists(carpeta):
            os.makedirs(carpeta)

        # Asegúrate de limpiar el nombre del archivo de caracteres especiales
        nombre_archivo = "todos_los_usuarios.csv".replace(" ", "_")
        ruta = os.path.join(carpeta, nombre_archivo)

        df.to_csv(ruta, index=False)
        
        print("Se descargó")
        return send_file(ruta, as_attachment=True)
    
    

OxiPulso/Autenticacion/views.py
from flask import (
   render_template,
   Blueprint,
   request,
   session,
   redirect,
   url_for 
)
from dotenv import load_dotenv
import os
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from OxiPulso import db
from OxiPulso.Autenticacion.models import Usuario

usuarios = Blueprint('usuarios', __name__)
administrador = Blueprint('administrador', __name__)
load_dotenv()


@usuarios.route('/registro', methods=['GET', 'POST'])
def registro():
    
    if request.method == 'POST':
        nombre = request.form.get('nombre')
        fechaNacimiento = datetime.strptime(request.form['fechaNacimiento'], '%Y-%m-%d').date()
        sexo = request.form.get('sexo')
        usuario = request.form.get('usuario')
        correo = request.form.get('email')
        contraseña = request.form.get('contraseña')
        confirmarContraseña = request.form.get('confirmarContraseña')

        # Verificaciones 
        if not nombre:
            return render_template("autenticacion/registro.html", alert = "Ingrese su nombre") 
        
        if not fechaNacimiento:
            return render_template("autenticacion/registro.html", alert = "Ingrese su fechaNacimiento") 
        
        if not sexo:
            return render_template("autenticacion/registro.html", alert = "Ingrese su sexo")
        
        if not usuario:
            return render_template("autenticacion/registro.html", alert = "Ingrese un usuario")
        
        if not correo:
            return render_template("autenticacion/registro.html", alert = "Ingrese un correo")
        
        if not contraseña:
            return render_template("autenticacion/registro.html", alert = "Ingrese una contraseña")
        
        if not confirmarContraseña:
            return render_template("autenticacion/registro.html", alert = "Repita la contraseña")

        if contraseña != confirmarContraseña:
            return render_template("autenticacion/registro.html", alert = "Las claves no coinciden")
        
        try:
            nuevoUsuario = Usuario(nombre, fechaNacimiento, sexo, usuario, correo, generate_password_hash(contraseña), datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
            db.session.add(nuevoUsuario)
            db.session.commit()
            
            
            session['usuario_id'] = nuevoUsuario.id
            
            db.session.close()
            return render_template("index.html", success = "Usuario registrado correctamente")
        
        except Exception as e:
            db.session.rollback()
            return render_template("autenticacion/registro.html", alert = "Usuario y/o correo ya existen")
        
    return render_template("autenticacion/registro.html")

@usuarios.route('/iniciarSesion', methods=['GET', 'POST'])
def iniciarSesion():
    session.clear()
    if request.method == 'POST':
        usuario = request.form.get('usuario')
        if os.getenv("USER_ADMIN") == usuario and  os.getenv("PASSWORD_ADMIN") == request.form.get('contraseña'):
           return render_template("administrador/admonvista.html", success="Ha iniciado sesion como administrador")
        usuario = Usuario.query.filter_by(usuario = request.form.get('usuario')).first()
        # Verificariones
        if not request.form.get('usuario'):
            return render_template("autenticacion/iniciarSesion.html", alert = "Ingrese un usuario")
           
        if not request.form.get('contraseña'):
            return render_template("autenticacion/iniciarSesion.html", alert = "Ingrese una contraseña")
        
        
        if not usuario:
            return render_template("autenticacion/iniciarSesion.html", alert = "El usuario no existe")

    
        if not usuario or not check_password_hash(usuario.contraseña, request.form.get('contraseña')):
            return render_template('autenticacion/iniciarSesion.html', alert = "Contraseña invalida")
        
        elif os.getenv("USER_ADMIN") == usuario and os.getenv("PASSWORD_ADMIN") == request.form.get('contraseña'):
           return render_template("administrador/admon.html", alert = "Ingrese una contraseña")
        
        session['usuario_id'] = usuario.id
        
        return render_template('index.html', success="Ha iniciado sesion")
    
    return render_template("autenticacion/iniciarSesion.html")

@usuarios.route('/cerrarSesion')
def cerrarSesion():
    session['usuario_id'] = None
    return redirect(url_for('base.index'))


@administrador.route('/admonvista')
def admonvista():
    return render_template('administrador/admonvista.html')

OxiPulso/templates/autenticacion/iniciarSesion.html
{% extends "base.html" %}
{% block title %}Iniciar Sesión{% endblock %}

{% block content %}
<main class="mt-28 mb-10">
    <h1 class="font-bold text-blue-700 text-4xl text-center mb-8">Iniciar Sesión</h1>
    <form action="/iniciarSesion" method="POST" class="max-w-md mx-auto bg-white p-8 rounded-lg shadow-md ">
     
        <div class="mb-5">
            <label for="usuario" class="block mb-2 text-sm font-medium text-gray-900 ">Tu usuario</label>
            <input type="text" id="usuario" name="usuario" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " placeholder="Usuario" required />
          </div>
      <div class="mb-5">
        <label for="contraseña" class="block mb-2 text-sm font-medium text-gray-900 ">Contraseña</label>
        <input type="password" id="password" name="contraseña" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " required />
      </div>
     
      
      <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center   ">Iniciar Sesión</button>
      <div class="text-center mt-5">
        <p class="text-sm font-medium text-gray-900 ">No tienes una cuenta? <a href="{{ url_for('usuarios.registro') }}" class="text-blue-600 hover:underline ">Registrate</a></p>
      </div>
    </form>
  </main>
  {% endblock %}

OxiPulso/templates/autenticacion/registro.html
{% extends "base.html" %}
{% block title %}Registro{% endblock %}

{% block content %}
<main class="mt-28 mb-10">
    <h1 class="font-bold text-blue-700 text-4xl text-center mb-8">Regístrate</h1>
    <form action="/registro" method="POST" class="max-w-md mx-auto bg-white p-8 rounded-lg shadow-md ">
      <div class="mb-5">
        <label for="nombre" class="block mb-2 text-sm font-medium text-gray-900 ">Nombre Completo</label>
        <input type="text" id="nombre" name="nombre" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " placeholder="Nombre Completo" required />
      </div>
      <div class="mb-5">
        <label for="fechaNacimiento" class="block mb-2 text-sm font-medium text-gray-900 ">Fecha de Nacimiento</label>
        <input type="date" id="fechaNacimiento" name="fechaNacimiento" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " min="1900-01-01" max="2006-12-31" required />
      </div>
      <div class="mb-5">
        <label for="sexo" class="block mb-2 text-sm font-medium text-gray-900 ">Sexo</label>
        <select id="sexo" name="sexo" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " required>
          <option value="" disabled selected>Selecciona tu sexo</option>
          <option value="Masculino">Masculino</option>
          <option value="Femenino">Femenino</option>
          <option value="Otro">Otro</option>
        </select>
      </div>
      <div class="mb-5">
        <label for="usuario" class="block mb-2 text-sm font-medium text-gray-900 ">Tu usuario</label>
        <input type="text" id="usuario" name="usuario" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " placeholder="Usuario" required />
      </div>
      <div class="mb-5">
        <label for="email" class="block mb-2 text-sm font-medium text-gray-900 ">Tu email</label>
        <input type="email" id="email" name="email" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " placeholder="nombre@ejemplo.com" required />
      </div>
      <div class="mb-5">
        <label for="contraseña" class="block mb-2 text-sm font-medium text-gray-900 ">Contraseña</label>
        <input type="password" id="contraseña" name="contraseña" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " required />
      </div>
      <div class="mb-5">
        <label for="confirmarContraseña" class="block mb-2 text-sm font-medium text-gray-900 ">Repite tu contraseña</label>
        <input type="password" id="confirmarContraseña" name="confirmarContraseña" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5       " required />
      </div>
      <div class="flex items-center mb-5">
        <input type="checkbox" id="terms" class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded    ">
        <label for="terms" class="ml-2 text-sm font-medium text-gray-900 ">Acepto los <a href="#" class="text-blue-600 hover:underline ">términos y condiciones</a></label>
      </div>
      <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center   ">Registrar cuenta</button>
      <div class="text-center mt-5">
        <p class="text-sm font-medium text-gray-900 ">Ya tienes una cuenta? <a href="{{ url_for('usuarios.iniciarSesion') }}" class="text-blue-600 hover:underline ">Inicia sesión</a></p>
      </div>
    </form>
  </main>
{% endblock %}