OxiPulso/Mediciones/models.py
from OxiPulso import db
import pandas as pd
import os
from OxiPulso.Autenticacion.models import Usuario
from flask import send_file
import random
from datetime import date

class Mediciones(db.Model):
    _tablename_ = "mediciones"
    id = db.Column(db.Integer, primary_key=True)
    usuario_id = db.Column(db.Integer, db.ForeignKey('usuarios.id'), nullable=False)
    bpm = db.Column(db.Integer, nullable=False)
    spo2 = db.Column(db.Integer, nullable=False)
    fecha = db.Column(db.Date, nullable=False)
    hora = db.Column(db.Time, nullable=False)
    usuario = db.relationship('Usuario', backref=db.backref('mediciones', lazy=True))


    def __init__(self, usuario_id, bpm, spo2, fecha, hora):
        self.usuario_id = usuario_id
        self.bpm = bpm
        self.spo2 = spo2
        self.fecha = fecha
        self.hora = hora
    
    def __repr__(self):
        return f"BPM: {self.bpm}\nSPO2: {self.spo2}\nFecha: {self.fecha}\nHora: {self.hora}"
    
    def to_dict(self):
        return {
            'id': self.id,
            'usuario_id': self.usuario_id,
            'bpm': self.bpm,
            'spo2': self.spo2,
            'fecha': self.fecha.isoformat(),
            'hora': str(self.hora.strftime('%H:%M'))
        }
    
    def to_dict_admon(self):
        return {
            'id': self.id,
            'usuario_nombre':self.usuario.nombre,
            'bpm': self.bpm,
            'spo2': self.spo2,
            'fecha': self.fecha.isoformat(),

        }
        
    def to_dict_all(self):
        nacimiento = self.usuario.fechaNacimiento
        hoy = date.today()
        edad = hoy.year - nacimiento.year - ((hoy.month, hoy.day) < (nacimiento.month, nacimiento.day))

        return {
            'id': self.id,
            'nombre':self.usuario.nombre,
            'edad':edad,
            'sexo':self.usuario.sexo,
            'bpm': self.bpm,
            'spo2': self.spo2,
            'fecha': self.fecha.isoformat(),

        }

    
    @classmethod
    def obtener_datos(cls, id):
        datos = cls.query.filter_by(usuario_id=id).all()
        datos_dict = [dato.to_dict() for dato in datos]
        # print(datos_dict)
        return datos_dict
        
    @classmethod
    def obtener_datos_admon(cls):
        datos = cls.query.all()
        datos_dict_admon = [dato.to_dict_admon() for dato in datos]
        # print(datos_dict_admon)
        return datos_dict_admon
    
    @classmethod
    def obtener_todos_datos(cls):
        datos = cls.query.all()
        datos_dict_admon = [dato.to_dict_all() for dato in datos]
        # print(datos_dict_admon)
        return datos_dict_admon


    
    @classmethod
    def descargar_csv(cls, usuario_id):
        usuario = Usuario.query.filter_by(id=usuario_id).first()
        
        if not usuario:
            return "Usuario no encontrado", 404
        
        datos = db.session.query(Usuario, Mediciones).join(
            Mediciones, Usuario.id == Mediciones.usuario_id
        ).with_entities(
            Usuario.nombre, Mediciones.bpm, Mediciones.spo2, Mediciones.hora, Mediciones.fecha
        ).filter(
            Usuario.id == usuario_id
        ).all()

        df = pd.DataFrame(datos, columns=['Nombre', 'BPM', 'SPO2', 'Hora', 'Fecha'])

        # Define la carpeta correcta
        base_dir = os.path.dirname(os.path.abspath(__file__))  # Base directory of the script
        carpeta = os.path.join(base_dir, 'Oxipulso', 'archivos')
        
        if not os.path.exists(carpeta):
            os.makedirs(carpeta)

        # Asegúrate de limpiar el nombre del archivo de caracteres especiales
        nombre_archivo = f"{usuario.nombre}.csv".replace(" ", "_")
        ruta = os.path.join(carpeta, nombre_archivo)

        df.to_csv(ruta, index=False)
        
        print("Se descargó")
        return send_file(ruta, as_attachment=True)
    
    @classmethod
    def descargar_csv_usuario(cls, usuario_id):
        usuario = Usuario.query.filter_by(id=usuario_id).first()
    
        datos = db.session.query(Usuario, Mediciones).join(Mediciones,
            Usuario.id == Mediciones.usuario_id).with_entities(Usuario.nombre, Mediciones.bpm, Mediciones.spo2, Mediciones.hora, Mediciones.fecha).filter(Usuario.id == usuario_id).all()

    
        df = pd.DataFrame(datos, columns=['Nombre', 'BPM', 'SPO2', 'Hora', 'Fecha'])

        carpeta = 'Oxipulso/archivos'
        
        if not os.path.exists(carpeta):
            os.makedirs(carpeta)

        ruta = os.path.join(carpeta, f"{usuario.nombre}.csv")

        print("Se descargó")
        # Convertimos el dataframe en un archivo excel y lo guardamos
        df.to_csv(ruta, index=False)
        return send_file(ruta, as_attachment=True)
        
    @classmethod
    def descargar_csv_all(cls):
        datos = db.session.query(Usuario, Mediciones).join(
            Mediciones, Usuario.id == Mediciones.usuario_id
        ).with_entities(
            Usuario.nombre, Mediciones.bpm, Mediciones.spo2, Mediciones.hora, Mediciones.fecha
        ).all()
        print(datos)
        df = pd.DataFrame(datos, columns=['Nombre', 'BPM', 'SPO2', 'Hora', 'Fecha'])
        
        # Define la carpeta correcta
        base_dir = os.path.dirname(os.path.abspath(__file__))  
        carpeta = os.path.join(base_dir, 'archivos')
        
        if not os.path.exists(carpeta):
            os.makedirs(carpeta)

        # Asegúrate de limpiar el nombre del archivo de caracteres especiales
        nombre_archivo = "todos_los_datos.csv".replace(" ", "_")
        ruta = os.path.join(carpeta, nombre_archivo)

        df.to_csv(ruta, index=False)
        
        print("Se descargó")
        return send_file(ruta, as_attachment=True)
    
    @classmethod
    def descargar_datos_usuario(cls, usuario_id):
        usuario = Usuario.query.filter_by(id=usuario_id).first()
        datos = cls.query.filter_by(usuario_id=usuario_id).all()
        datos_dict = [dato.to_dict() for dato in datos]
        return datos_dict
    

OxiPulso/Mediciones/views.py
from flask import (
    render_template,
    Blueprint,
    request,
    jsonify,
    session,
    redirect,
    url_for 
)
from OxiPulso.Mediciones.models import Mediciones

from OxiPulso.funciones import init_mqtt, wait_for_message
from OxiPulso import app, db
from datetime import datetime
from dotenv import load_dotenv
import os

load_dotenv()
# Iniciar MQTT
topic = os.environ.get('MQTT_TOPIC')
mqtt_client = init_mqtt(app, topic)


mediciones = Blueprint('mediciones', __name__)


@mediciones.route('/mediciones', methods=['GET', 'POST'])
def medicion():
    return render_template("mediciones/mediciones.html")

@mediciones.route('/tutorial')
def tutorial():
    return render_template("mediciones/tutorial.html")

@app.route('/mediciones/medir', methods=['POST'])
def publish_message():
    request_data = request.form['message']
    print(request_data)
    publish_result = mqtt_client.publish(topic, request_data)
    print(publish_result)
    
    # Espera a que se publique el valor medido
    measured_value = wait_for_message()
    # measured_value = {"HR":51,"SPO2":90}
    # measured_value = None
    
    if measured_value is not None:
        
        if "error" in measured_value:
            print(measured_value)
            return jsonify(success=False, error=measured_value["error"])
        
        print(measured_value)
        
        usuario_id = session.get('usuario_id')
        if usuario_id:
            try:
                nueva_medicion = Mediciones(
                    usuario_id=usuario_id,
                    bpm=measured_value["HR"],
                    spo2=measured_value["SPO2"],
                    fecha=datetime.today().strftime("%Y-%m-%d"),
                    hora=datetime.now().strftime("%H:%M:%S")
                )
                
                db.session.add(nueva_medicion)
                db.session.commit()
           
            except Exception as e:
               
                db.session.rollback()
                return jsonify(success=False, error="Error inesperado al guardar la medición")
        
        return jsonify(success=True, hr=measured_value["HR"], spo2=measured_value["SPO2"])
    else:
        return jsonify(success=False, error="No se recibió el valor del sensor a tiempo")
    
@mediciones.route('/historial')
def historial():
    usuario_id = session.get('usuario_id')
    if usuario_id:
        mediciones = Mediciones.obtener_datos(id=usuario_id)
        # print(mediciones)
        return render_template("mediciones/historial.html", mediciones=mediciones)
        # return render_template("mediciones/historial.html")
    else:
        return redirect(url_for('usuarios.iniciarSesion'))
    
@mediciones.route('/mediciones/historial/datos')
def historial_obtener_datos():
    usuario_id = session.get('usuario_id')
    if usuario_id:
        mediciones = Mediciones.obtener_datos(id=usuario_id)
        #return render_template("mediciones/historial.html", mediciones=mediciones)
        return jsonify(success=True, mediciones=mediciones)
    else:
        return redirect(url_for('usuarios.iniciarSesion'))
    

@mediciones.route('/mediciones/descargar')
def descargar():
    usuario_id = session.get('usuario_id')
    if usuario_id:
        return Mediciones.descargar_csv(usuario_id)
    else:
        return jsonify(success=False, error="No se ha iniciado sesión")
    

@mediciones.route('/mediciones/resumen')
def resumen():   
    return render_template("mediciones/resumen.html")
    
    

OxiPulso/templates/mediciones/historial.html
{% extends "base.html" %}
{% block title %}Historial{% endblock %}

{% block content%}
<main class="mt-28 mb-20">
<div class="overflow-x-auto bg-white shadow-md sm:rounded-lg p-4 tabla-scroll">
  <button
      type="button"
      class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center mb-6"
    >
    <a href="{{ url_for('mediciones.descargar') }}">Descargar Mis Datos</a>
    </button> 
    <table id="productTable" class="min-w-full divide-y divide-gray-200">
      <thead>
        <tr class="bg-blue-700 text-xs text-white font-bold uppercase">
                <th onclick="ordenarColumna(0)" class="px-6 py-3 text-left cursor-pointer">
                  Bpm
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th onclick="ordenarColumna(1)" class="px-6 py-3 text-left cursor-pointer">
                  Spo2
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th onclick="ordenarColumna(2)" class="px-6 py-3 text-left cursor-pointer">
                  Hora
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
                <th onclick="ordenarColumna(3)" class="px-6 py-3 text-left cursor-pointer">
                  Fecha
                  <svg class="w-3 h-3 inline-block ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                  </svg>
                </th>
              </tr>
        </tr>
      </thead>
      <tbody id="tableBody">
        <!-- Aquí se insertarán las filas de la tabla -->
      </tbody>
    </table>
  </div>

  <div id="paginacion" class="pagination flex justify-center items-center mt-4"></div>
</main>


{% endblock %}

OxiPulso/templates/mediciones/mediciones.html
{% extends "base.html" %}
{% block title %}Medición{% endblock %}

{% block content%}
<main class="mt-28 mb-20">
    <h3 class="font-bold text-blue-700 text-4xl text-center mb-2">Para obtener una medición pulse el botón</h3>
    <form id="measurementForm" class="max-w-md mx-auto bg-white p-8 rounded-lg">
        <input type="hidden" name="message" value="medir">
        <button type="submit" id="submitButton" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Obtener Medición</button>
    </form>

    <!-- Card de Medición -->
    <div id="measurementCard" class="max-w-md mx-auto bg-white p-8 rounded-lg shadow-md mt-10 hidden">
        <div class="flex items-center mb-4">
            <div>
                <div class="flex">
                    <i class="ph ph-heartbeat text-red-500 text-3xl mr-3"></i>
                    <h4 class="text-xl font-semibold text-gray-900">Frecuencia Cardíaca</h4>
                </div>
                <p class="text-lg text-gray-600 ml-10"><span id="bpm" class="value">80</span> bpm</p>
            </div>
        </div>
        <div class="flex items-center mb-4">
            <div>
                <div class="flex">
                    <i class="ph ph-wave-sawtooth text-blue-500 text-3xl mr-3"></i>
                    <h4 class="text-xl font-semibold text-gray-900">Oxígeno en Sangre</h4>
                </div>
                <p class="text-lg text-gray-600 ml-10"><span id="spo2" class="value">99</span> %</p>
            </div>
        </div>
        
        <button id="newMeasurementButton" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Nueva Medición</button>
            
    </div>

    <!-- Información útil -->
    <section class="max-w-screen-md mx-auto mt-10 p-4 bg-white rounded-lg">
        <h3 class="text-2xl font-bold text-blue-700 mb-4">Consejos para una buena salud cardíaca</h3>
        <ul class="list-disc pl-5 text-gray-600">
            <li>Mantén una dieta equilibrada rica en frutas, verduras y granos enteros.</li>
            <li>Realiza ejercicio regularmente, al menos 150 minutos de actividad moderada cada semana.</li>
            <li>Evita fumar y reduce el consumo de alcohol.</li>
            <li>Controla tu presión arterial y niveles de colesterol.</li>
            <li>Gestiona el estrés mediante técnicas de relajación como la meditación o el yoga.</li>
        </ul>
    </section>

    <section class="max-w-screen-md mx-auto mt-10 p-4 bg-white rounded-lg">
        <h3 class="text-2xl font-bold text-blue-700 mb-4">Beneficios del seguimiento del oxígeno en sangre</h3>
        <ul class="list-disc pl-5 text-gray-600">
            <li>Ayuda a detectar problemas respiratorios de manera temprana.</li>
            <li>Es crucial para personas con condiciones como EPOC o apnea del sueño.</li>
            <li>Permite monitorear la respuesta del cuerpo al ejercicio y a la altitud.</li>
            <li>Contribuye a evaluar la eficacia de tratamientos médicos.</li>
            <li>Proporciona tranquilidad al saber que tus niveles de oxígeno son adecuados.</li>
        </ul>
    </section>
</main>

{% endblock %}

OxiPulso/templates/mediciones/resumen.html
{% extends "base.html" %}
{% block title %}Resumen{% endblock %}

{% block content %}
<main>
    <div class="flex flex-col items-center justify-center min-h-screen pt-32">
        <span class="self-center text-2xl text-blue-700 font-semibold whitespace-nowrap">Mi Resumen de Mediciones</span>
        <!-- Contenedor de la gráfica -->
        <canvas id="medicionesChart" width="400" height="200"></canvas>
    </div>
</main>

<!-- Incluye Chart.js desde un CDN -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    // Función para cargar datos desde la API
    async function cargarDatos() {
      try {
        const response = await fetch('/mediciones/historial/datos'); // Tu API
        const data = await response.json();
  
        if (data.mediciones) {
          const mediciones = data.mediciones;
  
          // Organizar datos para la gráfica
          const fechas = mediciones.map(m => m.fecha); // Extraer las fechas
          const bpms = mediciones.map(m => m.bpm); // Extraer BPM
          const spo2s = mediciones.map(m => m.spo2); // Extraer SPO2
  
          // Crear la gráfica
          const ctx = document.getElementById('medicionesChart').getContext('2d');
          new Chart(ctx, {
            type: 'line',
            data: {
              labels: fechas, // Eje X: Fechas
              datasets: [
                {
                  label: 'BPM',
                  data: bpms, // Valores de BPM
                  borderColor: 'rgba(75, 192, 192, 1)',
                  backgroundColor: 'rgba(75, 192, 192, 0.2)',
                  borderWidth: 2,
                },
                {
                  label: 'SPO2',
                  data: spo2s, // Valores de SPO2
                  borderColor: 'rgba(153, 102, 255, 1)',
                  backgroundColor: 'rgba(153, 102, 255, 0.2)',
                  borderWidth: 2,
                },
              ],
            },
            options: {
              responsive: true,
              plugins: {
                legend: {
                  position: 'top',
                },
                tooltip: {
                  enabled: true,
                },
              },
              scales: {
                x: {
                  title: {
                    display: true,
                    text: 'Fecha',
                  },
                },
                y: {
                  title: {
                    display: true,
                    text: 'Valores',
                  },
                  beginAtZero: true,
                },
              },
            },
          });
        }
      } catch (error) {
        console.error('Error al cargar los datos:', error);
      }
    }
  
    // Llamar a la función para cargar los datos cuando la página esté lista
    document.addEventListener('DOMContentLoaded', cargarDatos);
  </script>
  
{% endblock %}
s

OxiPulso/templates/mediciones/tutorial.html
{% extends "base.html" %}
{% block title %}Tutorial{% endblock %}

{% block content%}
<main>
    <div class="flex flex-col items-center justify-center min-h-screen pt-32">
        <span class="self-center text-2xl text-blue-700 font-semibold whitespace-nowrap  ">¿Cómo utilizar Oxipulso para realizar sus mediciones?</span>

        <div class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100    mb-8">
            <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" src="https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/321310_2200-1200x628.jpg" alt="">
            <div class="flex flex-col justify-between p-4 leading-normal">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">Dirigase al apartado "Medicion"</h5>
                <p class="mb-3 font-normal text-gray-700 ">Hallará el Botón que inicializa la medicion del Pulso Cárdiaco y del Spo2</p>
            </div>
        </div>
    
        <div class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100    mb-8">
            <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" src="https://cdn.sparkfun.com/assets/learn_tutorials/5/7/7/MAX30105_Pulse_Oximetry.jpg" alt="">
            <div class="flex flex-col justify-between p-4 leading-normal">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">Apoye su dedo en el dispositivo de medición</h5>
                <p class="mb-3 font-normal text-gray-700 ">Intente no moverse ni haga movimientos bruscos que afecten la medición</p>
            </div>
        </div>

        <div class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100    mb-8">
            <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" src="https://cdn.sparkfun.com/assets/learn_tutorials/5/7/7/MAX30105_Pulse_Oximetry.jpg" alt="">
            <div class="flex flex-col justify-between p-4 leading-normal">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">Mantenga su dedo en el sensor el tiempo por el tiempo indicado</h5>
                <p class="mb-3 font-normal text-gray-700 ">No levante su dedo hasta que la medición ya se haya hecho, si hay algun error saltará una advertencia</p>
            </div>
        </div>

        <div class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100    mb-8">
            <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" src="https://cdn.sparkfun.com/assets/learn_tutorials/5/7/7/MAX30105_Pulse_Oximetry.jpg" alt="">
            <div class="flex flex-col justify-between p-4 leading-normal">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">Su medición estará completa cuando salte la alerta</h5>
                <p class="mb-3 font-normal text-gray-700 ">Una vez que haya salido el valor de su medición ya puede retirar el dedo y verificar el valor de su medición el el historial o en su correo electrónico</p>
            </div>
        </div>
    </div>
    </div>
</main>
{% endblock %}